# Generated by Django 4.2 on 2025-11-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Health AI Model', max_length=100)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('date_loaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
