# Generated by Django 4.2 on 2025-11-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
