# Generated by Django 4.2 on 2025-11-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentprofile_student_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
