# Generated by Django 4.2 on 2025-11-12 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_studentprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='image',
        ),
    ]
