# Generated by Django 4.2 on 2025-11-09 15:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('heart_rate', models.IntegerField()),
                ('spo2', models.FloatField()),
                ('breathing_rate', models.FloatField()),
                ('temperature_c', models.FloatField()),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('prediction_score', models.FloatField(blank=True, null=True)),
                ('prediction_label', models.CharField(blank=True, max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
